version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    commit_message:
      prefix: "[dependabot]"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
